
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("858x529")
window.configure(bg = "#1600B7")


canvas = Canvas(
    window,
    bg = "#1600B7",
    height = 529,
    width = 858,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_background_img = PhotoImage(
    file=relative_to_assets("background_img.png"))
background_img = canvas.create_image(
    429.0,
    264.0,
    image=image_background_img
)

canvas.create_text(
    219.0,
    36.0,
    anchor="nw",
    text="Speech Emotion Recognition App",
    fill="#000000",
    font=("Inter Bold", 24 * -1)
)

canvas.create_rectangle(
    34.0,
    83.99999166549532,
    823.999951958147,
    86.00253295898438,
    fill="#0F0B0B",
    outline="")

button_background_img = PhotoImage(
    file=relative_to_assets("record_button.png"))
record_button = Button(
    image=button_background_img,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("record_button clicked"),
    relief="flat"
)
record_button.place(
    x=213.0,
    y=92.0,
    width=105.0,
    height=134.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("upload_button.png"))
upload_button = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("upload_button clicked"),
    relief="flat"
)
upload_button.place(
    x=534.0,
    y=92.0,
    width=105.0,
    height=134.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("trash_button.png"))
trash_button = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("trash_button clicked"),
    relief="flat"
)
trash_button.place(
    x=100.0,
    y=387.0,
    width=129.0,
    height=142.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("play_button.png"))
play_button = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("play_button clicked"),
    relief="flat"
)
play_button.place(
    x=359.0,
    y=387.0,
    width=130.0,
    height=142.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("analyze_button.png"))
analyze_button = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("analyze_button clicked"),
    relief="flat"
)
analyze_button.place(
    x=625.0,
    y=387.0,
    width=122.0,
    height=142.0
)

canvas.create_rectangle(
    122.0,
    240.0,
    736.0,
    357.0,
    fill="#D2CFE6",
    outline="")

canvas.create_text(
    381.0,
    357.0,
    anchor="nw",
    text="00:00",
    fill="#000000",
    font=("Inter", 20 * -1)
)
window.resizable(False, False)
window.mainloop()
